config/routes.rb
Rails.application.routes.draw do
  resources :benefits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
  before_action :set_benefit, only: [:show, :edit, :update, :destroy]

  # GET /benefits
  # GET /benefits.json
  def index
    @benefits = Benefit.all
  end

  # GET /benefits/1
  # GET /benefits/1.json
  def show
  end

  # GET /benefits/new
  def new
    @benefit = Benefit.new
  end

  # GET /benefits/1/edit
  def edit
  end

  # POST /benefits
  # POST /benefits.json
  def create
    @benefit = Benefit.new(benefit_params)

    respond_to do |format|
      if @benefit.save
        format.html { redirect_to @benefit, notice: 'Benefit was successfully created.' }
        format.json { render :show, status: :created, location: @benefit }
      else
        format.html { render :new }
        format.json { render json: @benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /benefits/1
  # PATCH/PUT /benefits/1.json
  def update
    respond_to do |format|
      if @benefit.update(benefit_params)
        format.html { redirect_to @benefit, notice: 'Benefit was successfully updated.' }
        format.json { render :show, status: :ok, location: @benefit }
      else
        format.html { render :edit }
        format.json { render json: @benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /benefits/1
  # DELETE /benefits/1.json
  def destroy
    @benefit.destroy
    respond_to do |format|
      format.html { redirect_to benefits_url, notice: 'Benefit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_benefit
      @benefit = Benefit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def benefit_params
      params.require(:benefit).permit(:name, :description, :active, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/benefits_helper.rb
module BenefitsHelper
end

app/views/benefits/_form.html.erb
<%= form_with(model: benefit, local: true) do |form| %>
  <% if benefit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(benefit.errors.count, "error") %> prohibited this benefit from being saved:</h2>

      <ul>
        <% benefit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.datetime_select :active %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/benefits/edit.html.erb
<h1>Editing Benefit</h1>

<%= render 'form', benefit: @benefit %>

<%= link_to 'Show', @benefit %> |
<%= link_to 'Back', benefits_path %>

app/views/benefits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Benefits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @benefits.each do |benefit| %>
      <tr>
        <td><%= benefit.name %></td>
        <td><%= benefit.description %></td>
        <td><%= benefit.active %></td>
        <td><%= link_to 'Show', benefit %></td>
        <td><%= link_to 'Edit', edit_benefit_path(benefit) %></td>
        <td><%= link_to 'Destroy', benefit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Benefit', new_benefit_path %>

app/views/benefits/new.html.erb
<h1>New Benefit</h1>

<%= render 'form', benefit: @benefit %>

<%= link_to 'Back', benefits_path %>

app/views/benefits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @benefit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @benefit.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @benefit.active %>
</p>

<p>
  <strong>image:</strong><br>
  <%= image_tag @benefit.image, width: '500' if @benefit.image.attached? %>
</p>

<%= link_to 'Edit', edit_benefit_path(@benefit) %> |
<%= link_to 'Back', benefits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benefits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>